id: '0efa6075-1a45-4d56-737c-08dd7ccec69f'
name: 'C3-X-DB-DV'
description: ''
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Spark.Databricks'
  version: '1.9.2'
sourceSystems:
  - id: 'f62b2a4a-3f59-4045-b1da-ee0d6b00592c'
    name: 'c4'
    isLinkedProject: true
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
propertyValues:
  - propertyId: 'f968226e-a2ad-4e3d-b381-c8daf473cc06'
    value: 'Python Logger'
